import './form.js'
import './input.js'
import '../src/bpmn.scss'
import '../src/bpmn/diagram-js.css'
import '../src/bpmn/css/bpmn.css'
import '../src/bpmn/css/bpmn-codes.css'
import '../src/bpmn/css/bpmn-embedded.css'